name: ci

on:
  push:
  pull_request:

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Lint
        run: flake8 src tests
      - name: Train (smoke)
        run: |
          python src/get_data.py
          python src/train.py
      - name: Test
        run: pytest -q
      - name: Docker build
        run: |
          docker build -t ${{ github.repository }}:${{ github.sha }} .
      - name: Docker login & push
        if: secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/mlops-app:${{ github.sha }}"
          docker tag ${{ github.repository }}:${{ github.sha }} $IMAGE
          docker push $IMAGE
